version: '3'

services:

  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    ports:
    - 443:443
    depends_on:
    - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx:1.0
    env_file: .env
    restart: always
      
  mariadb:
    container_name: mariadb
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - inception
    expose:
    - 3306
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb:1.0
    env_file: .env
    restart: always

  wordpress:
    container_name: wordpress
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    expose:
    - 9000
    depends_on: 
    - mariadb
    build: 
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress:1.0
    env_file: .env
    restart: always

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/bde-meij/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/bde-meij/data/mariadb'

networks:
  inception:
    name: inception

# can set args for containers
#   args:
#   - name=name
#   - pass=pass

# order of construction should be mariadb, wordpress, enginx